Version 2
• Change mount point for PBs from /home/civpb/PBs to /altroot/PBs
• Adjust user and group id of civpb to mimic outer user id
  This is needed to get write premissions in the mounted volume.

 The user calling 'pitbossctl create' will propagate its id into
 the container.
• Split confirm-popup into make-screenshot and confirm-popup
• Add supervisorctl-section to supervisord.conf.
  This is still WIP.

diff --git a/bin/pitbossctl b/bin/pitbossctl
--- a/bin/pitbossctl
+++ b/bin/pitbossctl
@@ -3,16 +3,45 @@
 # Wrapper to start and stop container of a PB.
 # 
 
-DOCKER="docker"
-IMAGE="pbserver"
-PATH_TO_CIV4="/home/$USER/Civ4"
-PATH_TO_PBs="/home/$USER/PBs"
-DOMAIN="_https_zulan.net"
+# Variant to run this script as root. Useful if docker group
+# doesn't contain this user, but this script can be called
+# without root password.
+#
+# Installation: 
+#       1. Set RUN_WITH_SUDO on 1
+#       2. Copy this file to /usr/local/bin/pitbossctl
+#       3. Add your username to ./sudoers.d/pitbossctl and copy file
+#           to /etc/sudoers.d/
+#
+#          (And change access on sudoers-File file to 0440.)
+#
+RUN_WITH_SUDO=1
+
+if [ "$RUN_WITH_SUDO" = "1" ] ; then
+	if [ ! $USER = "root" ] ; then
+		# This often fails due security policy
+		# sudo --preserve-env=DOCKER,IMAGE,PATH_TO_CIV4,PATH_TO_CIV4,DOMAIN $0 "$@"
+
+		# Handle ENV vars over above sudoers-file
+		sudo $0 "$@"
+
+		exit $?
+	fi
+	# Reset USER variable.
+	USER=$SUDO_USER
+fi
+
+
+DOCKER="${DOCKER:-sudo docker}"
+IMAGE="${IMAGE:-pbserver}"
+PATH_TO_CIV4="${PATH_TO_CIV4:-/home/$USER/Civ4}"
+PATH_TO_PBs="${PATH_TO_PBs:-/home/$USER/PBs}"
+DOMAIN="${DOMAIN:-_https_pb.zulan.net}"
 
 
 CMD="$1"
 GAMEID="$2"
-MOD="$3"
+MOD_NAME="$3"
 PORT1="$4"
 PORT2="$5"
 PORT3="$6"
@@ -27,11 +56,14 @@ CONTAINER="$DOCKER ps -q -n 1 --filter name=Civ4_${GAMEID}"
 
 print_help() {
 	echo -e "$0 {COMMAND} {OPTIONS} with\n\tCOMMAND\tOPTIONS"
-	echo -e "\tcreate\t\"{GAMEID}\" \"{MODNAME}\" {PB_SERVER_PORT} {PB_WWW_PORT} {PB_SHELL_PORT}"
+	echo -e "\tcreate\t\"{GAMEID}\" \"{MOD_NAME}\" {PB_SERVER_PORT} {PB_WWW_PORT} {PB_SHELL_PORT}"
 	echo -e "\t\t Initialization for first run. Creates docker container named \"Civ4_{GAMEID}\"\n"
-	echo -e "\tdelete\t\"{GAMEID} [force]\" "
+	echo -e "\tdelete\t\"{GAMEID} [--force]\" "
 	echo -e "\t\t Removes docker container named \"Civ4_{GAMEID}\"\n"
-	echo -e "\tstart\t\"{GAMEID}\" "
+	echo -e "\tlist [-a]"
+	echo -e "\t\t lists GAMEID for docker container named \"Civ4_*\"\n"
+	echo -e "\t\t Without -a only running instances will be listed.\n"
+	echo -e "\tstart\t\"{GAMEID}\" \"[MOD_NAME}\" "
 	echo -e "\tstop\t\"{GAMEID}\" "
 	echo -e "\tshell\t\"{GAMEID}\" "
 	echo -e "\t\t Open shell in running instance\"\n"
@@ -44,49 +76,86 @@ print_help() {
 }
 
 
-if [ "$CMD" = "-h" -o "$CMD" = "--help" -o "$CMD" = "help" ] ; then
-	echo -e "Usage:\n\n"
+if [ -z "$CMD" -o "$CMD" = "-h" -o "$CMD" = "--help" -o "$CMD" = "help" ] ; then
+	echo "Usage:"
 	print_help
 	exit 0
+fi
 
-elif [ "$CMD" = "create" ] ; then
-	#sudo $DOCKER run --name "Civ4_$GAMEID" \
-	sudo $DOCKER create --name "Civ4_$GAMEID" \
+if [ "$CMD" = "list" ] ; then
+	if [ "$2" == "-a" ] ; then
+		ALL_FLAG="-a"
+	fi
+	$DOCKER ps $ALL_FLAG --filter="name=Civ4_" | sed -n  "s/.*Civ4_\([^ ]*\).*/\1/p"
+	exit 0
+fi
+
+# All other commands require GAMEID
+if [ -z "$GAMEID" ] ; then
+	echo "No game id given"
+	exit -1
+fi
+
+if [ "$CMD" = "create" ] ; then
+	#$DOCKER run --name "Civ4_$GAMEID" \
+	$DOCKER create --name "Civ4_$GAMEID" \
 		-e GAMEID="$GAMEID" \
-		-e MOD="$MOD" \
+		-e MOD_NAME="$MOD_NAME" \
 		-e DOMAIN="$DOMAIN" \
 		-e WINEDEBUG=fixme-all \
+		-e NEW_UID="$(id -u $USER)" -e NEW_GID="$(id -g $USER)" \
 		-v "$PATH_TO_CIV4:/app/Civ4" \
-		-v "$PATH_TO_PBs:/home/civpb/PBs" \
+		-v "$PATH_TO_PBs:/altroot/PBs" \
 		-p "$PORT1:$PORT1"   -p "$PORT2:$PORT2"   -p "$PORT3:$PORT3" \
 	  "${IMAGE}" \
 		&& echo "Civ4_$GAMEID created"
 
 elif [ "$CMD" = "delete" ] ; then
-	if [ ! "$2" = "1" -o ! "$2" = "force" ] ; then
+	if [ ! "$3" = "--force" ] ; then
 		echo -e "This will delete the docker container 'Civ4_${GAMEID}'.\n" \
 			"Are you sure? y/n"
-		read FOO
+		read DELETE_CONTAINER
+		if [ "$DELETE_CONTAINER" != "y" ] ; then
+			exit -1
+		fi
 	fi
-	sudo $DOCKER container rm "Civ4_${GAMEID}"
+	$DOCKER container rm "Civ4_${GAMEID}"
 
-elif [ "$CMD" = "start" ] ; then 
-	sudo $DOCKER container start $(sudo $CONTAINER)
+elif [ "$CMD" = "start" ] ; then
+	if [ -n "$MOD_NAME" ] ; then
+		echo "TODO: Changing the mod name after creation is currently not supported"
+		echo "'docker start' does not allow to provide new environment variables..."
+	fi
+	$DOCKER container start "$($CONTAINER)"
 
-elif [ "$CMD" = "stop" ] ; then 
-	sudo $DOCKER container stop $(sudo $CONTAINER)
+elif [ "$CMD" = "debug" ] ; then
+	$DOCKER container start -ai "$($CONTAINER)"
 
-elif [ "$CMD" = "screenshot" ] ; then 
-	sudo $DOCKER exec -t -u civpb $(sudo $CONTAINER) /usr/local/bin/confirm-popup
-	sudo $DOCKER cp -L "$(sudo $CONTAINER):/tmp/popup_${GAMEID}.png" "/tmp/popup_${GAMEID}.png" \
-		&& sudo chown $USER:$USER "/tmp/popup_${GAMEID}.png"  \
-		&& ( which feh && feh "/tmp/popup_${GAMEID}.png" || true)
+elif [ "$CMD" = "stop" ] ; then
+	$DOCKER container stop "$($CONTAINER)"
 
-elif [ "$CMD" = "id" ] ; then 
-	echo $(sudo $CONTAINER)
+elif [ "$CMD" = "shell" ] ; then
+	$DOCKER exec -it "$($CONTAINER)" /bin/bash
 
-elif [ "$CMD" = "stop" ] ; then 
-	sudo $DOCKER attach $(sudo $CONTAINER)
+elif [ "$CMD" = "screenshot" ] ; then
+	$DOCKER exec -t -u civpb $($CONTAINER) /usr/local/bin/make-screenshot
+	$DOCKER cp -L "$($CONTAINER):/tmp/popup_${GAMEID}.png" - \
+		> "/tmp/popup_${GAMEID}.png"  # Piping may change file ownership
+
+	if [ $? -eq 0 -a -n "$(which feh 2>/dev/null)" ] ; then
+			if [ -n "$SUDO_USER" ] ; then
+				sudo chown $SUDO_USER:$SUDO_USER "/tmp/popup_${GAMEID}.png"
+				su $SUDO_USER feh "/tmp/popup_${GAMEID}.png"
+			else
+				feh "/tmp/popup_${GAMEID}.png"
+			fi
+		fi
+
+elif [ "$CMD" = "id" ] ; then
+	echo "$($CONTAINER)"
+
+elif [ "$CMD" = "attach" ] ; then
+	$DOCKER attach "$($CONTAINER)"
 
 else
 	echo "Command '$CMD' not defined. Allowed commands:"
diff --git a/files/run-pb-server b/files/run-pb-server
--- a/files/run-pb-server
+++ b/files/run-pb-server
@@ -8,9 +8,21 @@ GAMEID="${GAMEID:-PB1}"
 MOD="${MOD:-PB Mod_v9}"
 DOMAIN="${DOMAIN:-_http_localhost}"
 
+if [ -n "$NEW_UID" -a "$NEW_UID" != "$(id -u civpb)" ] ; then
+        echo "Adjust user and group id to match with values outside."
+
+        # Hm, not possible as NON-root! Lets handle it by super
+        #/usr/local/bin/fix-ids-in-container "$NEW_UID" "$NEW_GID"
+        sleep 4
+
+        # Quit and let process restart by supervisord
+        exit 0
+fi
+
+
 # Forge folder structure which mimics the http(s) path to reach the
 # save games over http(s). Will be needed to load a save game fast.
-BASEDIR_WITH_DOMAIN="/home/civpb/${DOMAIN}/pb"
+BASEDIR_WITH_DOMAIN="/altroot/${DOMAIN}/pb"
 ALTROOT_WITH_DOMAIN="$BASEDIR_WITH_DOMAIN/PBs/${GAMEID}"
 #       The http server needs to serve the files under pb/PBs/...
 # TODO: This (static) path generation should ne done outside of the image...
@@ -19,11 +31,11 @@ ALTROOT_WITH_DOMAIN="$BASEDIR_WITH_DOMAIN/PBs/${GAMEID}"
 # ALTROOT_WIN="Z:\\home\\civpb\\${DOMAIN}\\pb\\PBs\\${GAMEID}"
 ALTROOT_WIN=`echo "Z:${ALTROOT_WITH_DOMAIN}" | sed -e 's/[\/]/\\\\/g' `
 
-cd /home/civpb
+cd /altroot
 mkdir -p "$BASEDIR_WITH_DOMAIN"
 if [ ! -d "${BASEDIR_WITH_DOMAIN}/PBs" ] ; then
-	# ln -s "/home/${USER}/PBs/" "$BASEDIR_WITH_DOMAIN"
-	ln -s "/home/civpb/PBs/" "$BASEDIR_WITH_DOMAIN"
+    # ln -s "/home/${USER}/PBs/" "$BASEDIR_WITH_DOMAIN"
+    ln -s "/altroot/PBs/" "$BASEDIR_WITH_DOMAIN"
 fi
 
 # Note: If you want linking one level below 'PBs', e.g. linking 'PB1',
@@ -36,85 +48,86 @@ fi
 # […]
 #  "readfolders": [
 #   "..\\PB1\\Saves\\multi", 
-#	  "..\\PB1\\Saves\\pitboss\\auto", 
-#	  ".\\Saves\\multi"
+#      "..\\PB1\\Saves\\pitboss\\auto", 
+#      ".\\Saves\\multi"
 # ]
 # […]
 #
 
 # Check if proper ALTROOT is given
 if [ ! -f "${ALTROOT_WITH_DOMAIN}/pbSettings.json" ] ; then
-	echo "pbSettings.json not found in in '$ALTROOT_WITH_DOMAIN'"
+    echo "pbSettings.json not found in in '$ALTROOT_WITH_DOMAIN'"
   exit -1
 fi
 if [ ! -f "${ALTROOT_WITH_DOMAIN}/CivilizationIV.ini" ] ; then
-	echo "CivilizationIV.ini not found in in '$ALTROOT_WITH_DOMAIN'"
+    echo "CivilizationIV.ini not found in in '$ALTROOT_WITH_DOMAIN'"
   exit -1
 else
-	echo "Fix path in the ini file"
-	# Backslash fun...
-	ALTROOT_WIN2=`echo "Z:${ALTROOT_WITH_DOMAIN}" | sed -e 's/[\/]/\\\\\\\\/g' `
-	sed -i -e"s/PitbossSMTPLogin=.*/PitbossSMTPLogin=${ALTROOT_WIN2}/" "${ALTROOT_WITH_DOMAIN}/CivilizationIV.ini"
+    echo "Fix path in the ini file"
+    # Backslash fun...
+    ALTROOT_WIN2=`echo "Z:${ALTROOT_WITH_DOMAIN}" | sed -e 's/[\/]/\\\\\\\\/g' `
+    ALTROOT_WIN2=`echo "Z:${ALTROOT_WITH_DOMAIN}" | sed -e 's/[\/]/\\\\\\\\\\\\\\\\/g' `
+    sed -i -e"s/PitbossSMTPLogin=.*/PitbossSMTPLogin=${ALTROOT_WIN2}/" "${ALTROOT_WITH_DOMAIN}/CivilizationIV.ini"
 
-	echo "Contain PitbossSMTPLogin now proper path?!"
-	grep "PitbossSMTPLogin=" "${ALTROOT_WITH_DOMAIN}/CivilizationIV.ini"
-	echo -e "\n\n"
+    echo "Contain PitbossSMTPLogin now proper path?!"
+    grep "PitbossSMTPLogin=" "${ALTROOT_WITH_DOMAIN}/CivilizationIV.ini"
+    echo -e "\n\n"
 fi
 if [ ! -d "${ALTROOT_WITH_DOMAIN}/Saves/multi" -a \
-	! -d "${ALTROOT_WITH_DOMAIN}/Saves/Multi" ] ; then
-	echo "Folder 'Saves/multi' not found in in '$ALTROOT_WITH_DOMAIN'"
+    ! -d "${ALTROOT_WITH_DOMAIN}/Saves/Multi" ] ; then
+    echo "Folder 'Saves/multi' not found in in '$ALTROOT_WITH_DOMAIN'"
   exit -1
 fi
 
 
 cd "/app/Civ4/Beyond the Sword"
 if [ -f "Civ4BeyondSword_PitBoss_Zulan2.exe" ] ; then
-	CIV4BTS="Civ4BeyondSword_PitBoss_Zulan2.exe"
+    CIV4BTS="Civ4BeyondSword_PitBoss_Zulan2.exe"
 elif [ -f "Civ4BeyondSword_PitBoss2014.exe" ] ; then
-	CIV4BTS="Civ4BeyondSword_PitBoss2014.exe"
+    CIV4BTS="Civ4BeyondSword_PitBoss2014.exe"
 else
-	CIV4BTS="Civ4BeyondSword_PitBoss.exe"
+    CIV4BTS="Civ4BeyondSword_PitBoss.exe"
 fi
 
 
 # Avoid permanent reloads of (non-working) server
 # if it restarts too often
 wait_after_n() {
-	NUM_ALLOWED="${1:-10}"
-	WAIT_S="${2:-3600}"
-	RESTART_FILE="/tmp/NUM_RESTARTS"
+    NUM_ALLOWED="${1:-10}"
+    WAIT_S="${2:-3600}"
+    RESTART_FILE="/tmp/NUM_RESTARTS"
 
-	# Create file if required
-	[ -f "$RESTART_FILE" ] || echo "0" > "$RESTART_FILE"
+    # Create file if required
+    [ -f "$RESTART_FILE" ] || echo "0" > "$RESTART_FILE"
 
-	# Check if to many restarts was made
-	NUM_CURRENT=$(cat "$RESTART_FILE")
-	TIME_TOUCH=$(stat -c %Y "$RESTART_FILE")	
-	TIME_NOW=$(date +%s)	
-	if (( $TIME_NOW - $TIME_TOUCH < $WAIT_S && ${NUM_ALLOWED:-1} <= ${NUM_CURRENT:-0} )) ; then
-		echo "Too many restarts in the last $WAIT_S seconds."
-		echo "Idle some time before PBServer starts again..."
-		sleep "$WAIT_S"
-		echo "... continue after waiting"
+    # Check if to many restarts was made
+    NUM_CURRENT=$(cat "$RESTART_FILE")
+    TIME_TOUCH=$(stat -c %Y "$RESTART_FILE")    
+    TIME_NOW=$(date +%s)    
+    if (( $TIME_NOW - $TIME_TOUCH < $WAIT_S && ${NUM_ALLOWED:-1} <= ${NUM_CURRENT:-0} )) ; then
+        echo "Too many restarts in the last $WAIT_S seconds."
+        echo "Idle some time before PBServer starts again..."
+        sleep "$WAIT_S"
+        echo "... continue after waiting"
 
-		echo "0" > "$RESTART_FILE"
-	else
+        echo "0" > "$RESTART_FILE"
+    else
 
-		echo "Restart counter: $NUM_CURRENT"
+        echo "Restart counter: $NUM_CURRENT"
 
-		if (( $TIME_NOW - $TIME_TOUCH < $WAIT_S )) ; then
-			# Increase number if still in the same time window.
-			let NUM_CURRENT++
-		else
-			# Restart with new time window
-			NUM_CURRENT=0
-		fi
-		echo "$NUM_CURRENT" > "$RESTART_FILE"
-	fi
+        if (( $TIME_NOW - $TIME_TOUCH < $WAIT_S )) ; then
+            # Increase number if still in the same time window.
+            let NUM_CURRENT++
+        else
+            # Restart with new time window
+            NUM_CURRENT=0
+        fi
+        echo "$NUM_CURRENT" > "$RESTART_FILE"
+    fi
 }
 
-# wait_after_n 10 3600
-wait_after_n 2 120
+wait_after_n 10 3600
+# wait_after_n 2 120
 
 
 # Start fake X
@@ -134,9 +147,9 @@ xauth -q -f "/tmp/Xvfb_screen0.auth" "generate" "$DISPLAY" "." "trusted"
 #WINEDLLOVERRIDES=mscoree,mshtml,winemenubuilder.exe=d,gameui,msxml3=d,msxml3r=d \
 unbuffer \
   wine "$CIV4BTS" \
-	mod= "${MOD}"\" \
-	/ALTROOT="${ALTROOT_WIN}" \
-	| grep -v "FTranslator::AddText"
+    mod= "${MOD}"\" \
+    /ALTROOT="${ALTROOT_WIN}" \
+    | grep -v "FTranslator::AddText"
 
 # Note: "^FTranslator::AddText" does not match(?!)
 
